### ISSUE TITLE
This does not seem to be released on Hackage?

### ISSUE THREAD

**Issue by thsutton** [mxswd/webcloud#2]
Y u no release on hackage?

**Comment by thsutton** [comment]
bump

**Comment by christian-marie** [comment]
@mxswd no but seriously, we're using this in production (hah!).

Can we get commit access and upload it to hackage for you?

**Comment by thielema** [comment]
Publish or Perish! Yes, please release on Hackage!

**Comment by thsutton** [comment]
Done! https://hackage.haskell.org/package/webcloud-0.1.0.1
